#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <functional>
#include <stdexcept>
#include <cstdint>
#include <cstring>
#include "../assembler/demi_assembler.hpp"
#include "../assembler/elf32_writer.hpp"
#include "../assembler/lexer.hpp"
#include "../assembler/lowering.hpp"
#include "../assembler/parser.hpp"
#include "../assembler/assembler.hpp"
#include "../assembler/x86_backend.hpp"

void print_bytecode(const std::vector<uint8_t>& bytecode) {
    std::cout << "Generated bytecode (" << bytecode.size() << " bytes):\n";
    for (size_t i = 0; i < bytecode.size(); ++i) {
        if (i % 16 == 0) {
            std::cout << std::setw(4) << std::setfill('0') << std::hex << i << ": ";
        }
        std::cout << std::setw(2) << std::setfill('0') << std::hex << static_cast<int>(bytecode[i]) << " ";
        if ((i + 1) % 16 == 0 || i == bytecode.size() - 1) {
            std::cout << "\n";
        }
    }
    std::cout << std::dec; // Reset to decimal
}

struct TestCase {
    std::string name;
    std::function<void()> run;
};

[[noreturn]] void fail_test(const std::string& message) {
    throw std::runtime_error(message);
}

uint16_t read_u16(const std::vector<uint8_t>& bytes, size_t offset) {
    if (offset + 1 >= bytes.size()) {
        fail_test("ELF read_u16 out of range");
    }
    return static_cast<uint16_t>(bytes[offset]) |
           (static_cast<uint16_t>(bytes[offset + 1]) << 8);
}

uint32_t read_u32(const std::vector<uint8_t>& bytes, size_t offset) {
    if (offset + 3 >= bytes.size()) {
        fail_test("ELF read_u32 out of range");
    }
    return static_cast<uint32_t>(bytes[offset]) |
           (static_cast<uint32_t>(bytes[offset + 1]) << 8) |
           (static_cast<uint32_t>(bytes[offset + 2]) << 16) |
           (static_cast<uint32_t>(bytes[offset + 3]) << 24);
}

struct ELF32SectionHeaderView {
    uint32_t name = 0;
    uint32_t type = 0;
    uint32_t flags = 0;
    uint32_t offset = 0;
    uint32_t size = 0;
    uint32_t link = 0;
    uint32_t info = 0;
    uint32_t addralign = 0;
    uint32_t entsize = 0;
};

struct ELF32SymbolView {
    uint32_t name = 0;
    uint32_t value = 0;
    uint32_t size = 0;
    uint8_t info = 0;
    uint8_t other = 0;
    uint16_t shndx = 0;
};

struct ELF64SectionHeaderView {
    uint32_t name = 0;
    uint32_t type = 0;
    uint64_t flags = 0;
    uint64_t offset = 0;
    uint64_t size = 0;
    uint32_t link = 0;
    uint32_t info = 0;
    uint64_t addralign = 0;
    uint64_t entsize = 0;
};

uint64_t read_u64(const std::vector<uint8_t>& bytes, size_t offset) {
    if (offset + 7 >= bytes.size()) {
        fail_test("ELF read_u64 out of range");
    }
    uint64_t value = 0;
    for (size_t i = 0; i < 8; ++i) {
        value |= static_cast<uint64_t>(bytes[offset + i]) << (i * 8);
    }
    return value;
}

ELF32SectionHeaderView read_section_header(const std::vector<uint8_t>& elf, uint32_t shoff, uint16_t index) {
    const size_t base = static_cast<size_t>(shoff) + static_cast<size_t>(index) * 40;
    ELF32SectionHeaderView header;
    header.name = read_u32(elf, base + 0);
    header.type = read_u32(elf, base + 4);
    header.flags = read_u32(elf, base + 8);
    header.offset = read_u32(elf, base + 16);
    header.size = read_u32(elf, base + 20);
    header.link = read_u32(elf, base + 24);
    header.info = read_u32(elf, base + 28);
    header.addralign = read_u32(elf, base + 32);
    header.entsize = read_u32(elf, base + 36);
    return header;
}

std::string read_c_string(const std::vector<uint8_t>& bytes, uint32_t offset) {
    if (offset >= bytes.size()) {
        fail_test("String offset out of range");
    }
    std::string value;
    for (size_t i = offset; i < bytes.size() && bytes[i] != 0; ++i) {
        value.push_back(static_cast<char>(bytes[i]));
    }
    return value;
}

uint16_t find_section_index(const std::vector<uint8_t>& elf, const std::string& section_name) {
    const uint32_t shoff = read_u32(elf, 32);
    const uint16_t shnum = read_u16(elf, 48);
    const uint16_t shstrndx = read_u16(elf, 50);
    const auto shstr = read_section_header(elf, shoff, shstrndx);

    for (uint16_t index = 0; index < shnum; ++index) {
        const auto header = read_section_header(elf, shoff, index);
        const auto name = read_c_string(elf, shstr.offset + header.name);
        if (name == section_name) {
            return index;
        }
    }

    fail_test("Missing ELF section: " + section_name);
}

std::vector<uint8_t> read_section_bytes(const std::vector<uint8_t>& elf, const std::string& section_name) {
    const uint32_t shoff = read_u32(elf, 32);
    const auto index = find_section_index(elf, section_name);
    const auto header = read_section_header(elf, shoff, index);
    if (header.offset + header.size > elf.size()) {
        fail_test("Section extends beyond ELF size: " + section_name);
    }
    return std::vector<uint8_t>(elf.begin() + header.offset, elf.begin() + header.offset + header.size);
}

ELF32SymbolView read_symbol_entry(const std::vector<uint8_t>& bytes, size_t offset) {
    ELF32SymbolView symbol;
    symbol.name = read_u32(bytes, offset + 0);
    symbol.value = read_u32(bytes, offset + 4);
    symbol.size = read_u32(bytes, offset + 8);
    if (offset + 15 >= bytes.size()) {
        fail_test("ELF symbol entry out of range");
    }
    symbol.info = bytes[offset + 12];
    symbol.other = bytes[offset + 13];
    symbol.shndx = read_u16(bytes, offset + 14);
    return symbol;
}

ELF32SymbolView find_symbol(const std::vector<uint8_t>& elf, const std::string& symbol_name) {
    const uint32_t shoff = read_u32(elf, 32);
    const uint16_t symtab_index = find_section_index(elf, ".symtab");
    const auto symtab_header = read_section_header(elf, shoff, symtab_index);
    const auto strtab_header = read_section_header(elf, shoff, static_cast<uint16_t>(symtab_header.link));

    if (symtab_header.entsize != 16) {
        fail_test("Expected ELF32 symbol size of 16 bytes");
    }

    for (size_t offset = 0; offset < symtab_header.size; offset += symtab_header.entsize) {
        const auto symbol = read_symbol_entry(elf, symtab_header.offset + offset);
        const auto name = read_c_string(elf, strtab_header.offset + symbol.name);
        if (name == symbol_name) {
            return symbol;
        }
    }

    fail_test("Missing ELF symbol: " + symbol_name);
}

ELF64SectionHeaderView read_section_header64(const std::vector<uint8_t>& elf, uint64_t shoff, uint16_t index) {
    const size_t base = static_cast<size_t>(shoff) + static_cast<size_t>(index) * 64;
    ELF64SectionHeaderView header;
    header.name = read_u32(elf, base + 0);
    header.type = read_u32(elf, base + 4);
    header.flags = read_u64(elf, base + 8);
    header.offset = read_u64(elf, base + 24);
    header.size = read_u64(elf, base + 32);
    header.link = read_u32(elf, base + 40);
    header.info = read_u32(elf, base + 44);
    header.addralign = read_u64(elf, base + 48);
    header.entsize = read_u64(elf, base + 56);
    return header;
}

uint16_t find_section_index64(const std::vector<uint8_t>& elf, const std::string& section_name) {
    const uint64_t shoff = read_u64(elf, 40);
    const uint16_t shnum = read_u16(elf, 60);
    const uint16_t shstrndx = read_u16(elf, 62);
    const auto shstr = read_section_header64(elf, shoff, shstrndx);

    for (uint16_t index = 0; index < shnum; ++index) {
        const auto header = read_section_header64(elf, shoff, index);
        const auto name = read_c_string(elf, static_cast<uint32_t>(shstr.offset + header.name));
        if (name == section_name) {
            return index;
        }
    }

    fail_test("Missing ELF64 section: " + section_name);
}

std::vector<uint8_t> read_section_bytes64(const std::vector<uint8_t>& elf, const std::string& section_name) {
    const uint64_t shoff = read_u64(elf, 40);
    const auto index = find_section_index64(elf, section_name);
    const auto header = read_section_header64(elf, shoff, index);
    if (header.offset + header.size > elf.size()) {
        fail_test("ELF64 section extends beyond ELF size: " + section_name);
    }
    return std::vector<uint8_t>(elf.begin() + static_cast<std::ptrdiff_t>(header.offset), elf.begin() + static_cast<std::ptrdiff_t>(header.offset + header.size));
}

std::unique_ptr<Assembler::Program> parse_program_or_fail(const std::string& source) {
    Assembler::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    if (lexer.has_errors()) {
        std::ostringstream oss;
        oss << "Lexer errors:";
        for (const auto& error : lexer.get_errors()) {
            oss << "\n  " << error;
        }
        fail_test(oss.str());
    }

    Assembler::Parser parser(tokens);
    auto program = parser.parse();
    if (parser.has_errors()) {
        std::ostringstream oss;
        oss << "Parser errors:";
        for (const auto& error : parser.get_errors()) {
            oss << "\n  " << error;
        }
        fail_test(oss.str());
    }

    return program;
}

const Assembler::MemoryReferenceExpression& get_first_memory_operand_or_fail(const Assembler::Program& program) {
    if (program.statements.empty()) {
        fail_test("Program has no statements");
    }

    const auto* instruction = dynamic_cast<const Assembler::Instruction*>(program.statements.front().get());
    if (!instruction || instruction->operands.size() < 2) {
        fail_test("Expected first statement to be an instruction with a memory operand");
    }

    const auto* memory = dynamic_cast<const Assembler::MemoryReferenceExpression*>(instruction->operands[1].get());
    if (!memory) {
        fail_test("Expected second operand to be a memory reference");
    }

    return *memory;
}

void run_builtin_tests() {
    const std::vector<TestCase> tests = {
        {
            "parses_size_qualified_symbol_displacement_memory",
            []() {
                auto program = parse_program_or_fail("MOV EAX, dword [msg + 8]\n");
                const auto& memory = get_first_memory_operand_or_fail(*program);

                if (memory.size_hint_bits != 32) {
                    fail_test("Expected dword size hint");
                }
                if (!memory.symbol || memory.symbol->name != "msg") {
                    fail_test("Expected symbolic memory term 'msg'");
                }
                const auto* displacement = dynamic_cast<const Assembler::ImmediateExpression*>(memory.displacement.get());
                if (!displacement || displacement->value != 8) {
                    fail_test("Expected displacement of 8");
                }
            }
        },
        {
            "parses_indexed_memory_expression",
            []() {
                auto program = parse_program_or_fail("MOV EAX, [EAX + ECX*4 + 8]\n");
                const auto& memory = get_first_memory_operand_or_fail(*program);

                const auto* base = dynamic_cast<const Assembler::RegisterExpression*>(memory.base.get());
                const auto* index = dynamic_cast<const Assembler::RegisterExpression*>(memory.index.get());
                const auto* displacement = dynamic_cast<const Assembler::ImmediateExpression*>(memory.displacement.get());
                if (!base || base->name != "EAX") {
                    fail_test("Expected base register EAX");
                }
                if (!index || index->name != "ECX") {
                    fail_test("Expected index register ECX");
                }
                if (memory.scale != 4) {
                    fail_test("Expected scale of 4");
                }
                if (!displacement || displacement->value != 8) {
                    fail_test("Expected displacement of 8");
                }
            }
        },
        {
            "parses_negative_base_offset_memory",
            []() {
                auto program = parse_program_or_fail("MOV EAX, [EBP-4]\n");
                const auto& memory = get_first_memory_operand_or_fail(*program);

                const auto* base = dynamic_cast<const Assembler::RegisterExpression*>(memory.base.get());
                const auto* offset = dynamic_cast<const Assembler::ImmediateExpression*>(memory.offset.get());
                if (!base || base->name != "EBP") {
                    fail_test("Expected base register EBP");
                }
                if (!offset || offset->value != -4) {
                    fail_test("Expected simple offset of -4");
                }
            }
        },
        {
            "assembles_absolute_symbol_plus_displacement_memory",
            []() {
                auto program = parse_program_or_fail(".data\nmsg: DB 1\n.text\nMOV EAX, [msg + 4]\n");
                Assembler::AssemblerEngine assembler;
                auto bytecode = assembler.assemble(*program);
                if (assembler.has_errors()) {
                    std::ostringstream oss;
                    oss << "Assembly errors:";
                    for (const auto& error : assembler.get_errors()) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }
                if (bytecode.empty()) {
                    fail_test("Expected non-empty bytecode output");
                }
            }
        },
        {
            "lowering_records_symbolic_memory_relocation_addend",
            []() {
                auto program = parse_program_or_fail("MOV EAX, dword [msg + 4]\n");
                auto lowered = Assembler::lower_program(*program);
                if (lowered.relocations.size() != 1) {
                    fail_test("Expected exactly one relocation for symbolic memory operand");
                }
                const auto& relocation = lowered.relocations.front();
                if (relocation.symbol != "msg") {
                    fail_test("Expected relocation symbol 'msg'");
                }
                if (relocation.addend != 4) {
                    fail_test("Expected relocation addend of 4");
                }
                if (relocation.operand_index != 1) {
                    fail_test("Expected relocation on operand index 1");
                }
            }
        },
        {
            "elf32_writer_emits_relocatable_object_for_data_symbol",
            []() {
                auto program = parse_program_or_fail(".data\nextern_sym: .dd 0\nref: .dd extern_sym\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;
                std::vector<std::string> errors;
                Assembler::ELF32ObjectWriter writer;
                auto elf = writer.write_object(lowered, errors);
                if (!errors.empty()) {
                    std::ostringstream oss;
                    oss << "ELF writer errors:";
                    for (const auto& error : errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }
                if (elf.size() < 4 || elf[0] != 0x7F || elf[1] != 'E' || elf[2] != 'L' || elf[3] != 'F') {
                    fail_test("Expected ELF magic in object output");
                }

                if (elf[4] != 1 || elf[5] != 1) {
                    fail_test("Expected ELFCLASS32 little-endian object");
                }

                const uint16_t rel_data_index = find_section_index(elf, ".rel.data");
                const auto rel_data_header = read_section_header(elf, read_u32(elf, 32), rel_data_index);
                if (rel_data_header.type != 9) {
                    fail_test("Expected .rel.data to be SHT_REL");
                }
                if (rel_data_header.entsize != 8 || rel_data_header.size != 8) {
                    fail_test("Expected exactly one ELF32 relocation entry in .rel.data");
                }

                const auto rel_data = read_section_bytes(elf, ".rel.data");
                const uint32_t rel_offset = read_u32(rel_data, 0);
                const uint32_t rel_info = read_u32(rel_data, 4);
                if (rel_offset != 4) {
                    fail_test("Expected relocation offset 4 for second .dd entry");
                }
                if ((rel_info & 0xFF) != 1) {
                    fail_test("Expected relocation type R_386_32");
                }

                const auto extern_sym = find_symbol(elf, "extern_sym");
                const auto ref = find_symbol(elf, "ref");
                const uint16_t data_index = find_section_index(elf, ".data");
                if (extern_sym.shndx != data_index || extern_sym.value != 0) {
                    fail_test("Expected extern_sym to resolve to .data offset 0 in .symtab");
                }
                if (ref.shndx != data_index || ref.value != 4) {
                    fail_test("Expected ref to resolve to .data offset 4 in .symtab");
                }
            }
        },
        {
            "x86_backend_emits_text_section_bytes_for_simple_mov_ret",
            []() {
                auto program = parse_program_or_fail(".text\n_start:\nMOV EAX, 1\nRET\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_32);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                const auto text = read_section_bytes(artifact.bytes, ".text");
                const std::vector<uint8_t> expected = {0xB8, 0x01, 0x00, 0x00, 0x00, 0xC3};
                if (text != expected) {
                    std::ostringstream oss;
                    oss << "Unexpected .text bytes";
                    fail_test(oss.str());
                }
            }
        },
        {
            "x86_backend_remaps__start_symbol_to_encoded_text_offset",
            []() {
                auto program = parse_program_or_fail(".text\nMOV EAX, 1\n_start:\nRET\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_32);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                const auto start_symbol = find_symbol(artifact.bytes, "_start");
                const uint16_t text_index = find_section_index(artifact.bytes, ".text");
                if (start_symbol.shndx != text_index) {
                    fail_test("Expected _start to be defined in .text");
                }
                if (start_symbol.value != 5) {
                    fail_test("Expected _start symbol value to match encoded text byte offset 5");
                }
            }
        },
        {
            "x86_backend_emits_pc_relative_text_relocation_for_external_call",
            []() {
                auto program = parse_program_or_fail(".text\n.extern ext_fn\nCALL ext_fn\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_32);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                const auto text = read_section_bytes(artifact.bytes, ".text");
                const std::vector<uint8_t> expected = {0xE8, 0xFC, 0xFF, 0xFF, 0xFF};
                if (text != expected) {
                    fail_test("Expected CALL placeholder bytes with PC-relative addend");
                }

                const auto rel_text = read_section_bytes(artifact.bytes, ".rel.text");
                if (rel_text.size() != 8) {
                    fail_test("Expected one .rel.text entry for external CALL");
                }
                if (read_u32(rel_text, 0) != 1) {
                    fail_test("Expected CALL relocation to patch operand at .text+1");
                }
                if ((read_u32(rel_text, 4) & 0xFF) != 2) {
                    fail_test("Expected R_386_PC32 relocation for external CALL");
                }
            }
        },
        {
            "x86_backend_emits_base_displacement_memory_movs",
            []() {
                auto program = parse_program_or_fail(".text\nMOV EAX, [EBP-4]\nMOV [EBP-4], EAX\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_32);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                const auto text = read_section_bytes(artifact.bytes, ".text");
                const std::vector<uint8_t> expected = {0x8B, 0x45, 0xFC, 0x89, 0x45, 0xFC};
                if (text != expected) {
                    fail_test("Expected MOV load/store bytes for [EBP-4] memory subset");
                }
            }
        },
        {
            "x86_64_backend_emits_elf64_text_object",
            []() {
                auto program = parse_program_or_fail(".text\n_start:\nMOV RAX, 1\nRET\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf64;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_64);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86-64 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                if (artifact.bytes.size() < 5 || artifact.bytes[4] != 2) {
                    fail_test("Expected ELFCLASS64 object output");
                }

                const auto text = read_section_bytes64(artifact.bytes, ".text");
                const std::vector<uint8_t> expected = {0x48, 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00, 0xC3};
                if (text != expected) {
                    fail_test("Expected ELF64 .text bytes for MOV RAX,1 / RET");
                }
            }
        },
        {
            "x86_32_backend_assembles_hello_world_with_data_reference",
            []() {
                auto program = parse_program_or_fail(
                    ".data\n"
                    "msg: .string \"Hello, World!\"\n"
                    ".text\n"
                    "global _start\n"
                    "_start:\n"
                    "MOV EAX, 4\n"
                    "MOV EBX, 1\n"
                    "MOV ECX, msg\n"
                    "MOV EDX, 13\n"
                    "INT 0x80\n"
                    "MOV EAX, 1\n"
                    "MOV EBX, 0\n"
                    "INT 0x80\n");
                auto lowered = Assembler::lower_program(*program);
                lowered.target = Assembler::IRTarget::X86Elf32;

                Assembler::X86Backend backend(Assembler::X86BackendMode::X86_32);
                auto artifact = backend.emit(lowered);
                if (!artifact.ok()) {
                    std::ostringstream oss;
                    oss << "x86 backend errors:";
                    for (const auto& error : artifact.errors) {
                        oss << "\n  " << error;
                    }
                    fail_test(oss.str());
                }

                const auto text = read_section_bytes(artifact.bytes, ".text");
                if (text.size() != 34) {
                    fail_test("Expected .text section of 34 bytes for hello-world");
                }
                if (text[0] != 0xB8 || text[5] != 0xBB || text[10] != 0xB9 || text[15] != 0xBA) {
                    fail_test("Expected MOV reg,imm opcodes for hello-world syscall setup");
                }
                if (text[20] != 0xCD || text[21] != 0x80 || text[32] != 0xCD || text[33] != 0x80) {
                    fail_test("Expected INT 0x80 opcodes");
                }

                const auto rel_text = read_section_bytes(artifact.bytes, ".rel.text");
                if (rel_text.size() != 8) {
                    fail_test("Expected one .rel.text entry for MOV ECX,msg");
                }
                if (read_u32(rel_text, 0) != 11) {
                    fail_test("Expected msg relocation at .text+11 (ECX immediate offset)");
                }
                if ((read_u32(rel_text, 4) & 0xFF) != 1) {
                    fail_test("Expected R_386_32 relocation for msg");
                }

                const auto msg_sym = find_symbol(artifact.bytes, "msg");
                const uint16_t data_index = find_section_index(artifact.bytes, ".data");
                if (msg_sym.shndx != data_index) {
                    fail_test("Expected msg symbol in .data section");
                }
                if (msg_sym.value != 0) {
                    fail_test("Expected msg symbol at .data offset 0");
                }
            }
        }
    };

    size_t passed = 0;
    for (const auto& test : tests) {
        try {
            test.run();
            std::cout << "[PASS] " << test.name << "\n";
            ++passed;
        } catch (const std::exception& ex) {
            std::cerr << "[FAIL] " << test.name << "\n" << ex.what() << "\n";
            throw;
        }
    }

    std::cout << "\nBuilt-in assembler tests passed: " << passed << "/" << tests.size() << "\n";
}

int main(int argc, char* argv[]) {
    std::cout << "Testing DemiEngine Assembler\n";
    std::cout << "==========================\n\n";

    std::string test_code;

    if (argc > 1) {
        // Read from file
        std::ifstream file(argv[1]);
        if (!file.is_open()) {
            std::cerr << "Error: Could not open file " << argv[1] << std::endl;
            return 1;
        }

        std::ostringstream oss;
        oss << file.rdbuf();
        test_code = oss.str();
        std::cout << "Reading assembly from file: " << argv[1] << "\n\n";
    } else {
        try {
            run_builtin_tests();
            std::cout << "\nTest completed successfully!\n";
            return 0;
        } catch (const std::exception&) {
            return 1;
        }
    }

    std::cout << "Assembly source:\n" << test_code << "\n";

    // Step 1: Lexical analysis
    std::cout << "Step 1: Lexical Analysis\n";
    Assembler::Lexer lexer(test_code);
    auto tokens = lexer.tokenize();

    if (lexer.has_errors()) {
        std::cout << "Lexer errors:\n";
        for (const auto& error : lexer.get_errors()) {
            std::cout << "  " << error << "\n";
        }
        return 1;
    }

    std::cout << "Tokens generated: " << tokens.size() << "\n";

    // Print first few tokens for debugging
    std::cout << "First 10 tokens:\n";
    for (size_t i = 0; i < std::min(tokens.size(), size_t(10)); ++i) {
        std::cout << "  " << i << ": " << static_cast<int>(tokens[i].type) << " '" << tokens[i].text << "'\n";
    }
    std::cout << "\n";

    // Step 2: Parsing
    std::cout << "Step 2: Parsing\n";
    Assembler::Parser parser(tokens);
    auto ast = parser.parse();

    if (parser.has_errors()) {
        std::cout << "Parser errors:\n";
        for (const auto& error : parser.get_errors()) {
            std::cout << "  " << error << "\n";
        }
        return 1;
    }

    std::cout << "AST statements: " << ast->statements.size() << "\n\n";

    // Step 3: Code generation
    std::cout << "Step 3: Code Generation\n";
    Assembler::AssemblerEngine assembler;
    auto bytecode = assembler.assemble(*ast);

    if (assembler.has_errors()) {
        std::cout << "Assembly errors:\n";
        for (const auto& error : assembler.get_errors()) {
            std::cout << "  " << error << "\n";
        }
        return 1;
    }

    print_bytecode(bytecode);

    // Show symbol table
    const auto& symbols = assembler.get_symbols();
    if (!symbols.empty()) {
        std::cout << "\nSymbol table:\n";
        for (const auto& [name, symbol] : symbols) {
            std::cout << "  " << name << " = 0x" << std::hex << symbol.address << std::dec << "\n";
        }
    }

    std::cout << "\nTest completed successfully!\n";
    return 0;
}